version: '3.3'
services:
    application:
      container_name: application
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        prometheus:
          condition: service_healthy
        grafana:
          condition: service_healthy
      ports:
        - "8080:8080"
      volumes:
        - ./build/libs/:/tmp

    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      command:
        - --config.file=/etc/prometheus.yaml
        - --web.enable-remote-write-receiver
        - --enable-feature=exemplar-storage
      volumes:
        - ./config/prometheus/prometheus-config.yaml:/etc/prometheus.yaml
      ports:
        - "9090:9090"
      healthcheck:
        interval: 5s
        retries: 10
        test: wget --no-verbose --tries=1 --spider http://localhost:9090/status || exit 1

    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      depends_on:
        prometheus:
          condition: service_healthy
      volumes:
        - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
        - ./config/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/main.yaml
        - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        - GF_AUTH_DISABLE_LOGIN_FORM=true
      ports:
        - "3000:3000"
      healthcheck:
        interval: 5s
        retries: 10
        test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1