global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring-actuator-promethes'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['application:8080']